services:
  llm-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - API_GATEWAY_URL=https://scpgq9wnh1.execute-api.us-east-1.amazonaws.com/prod/generate
    volumes:
      - ./logs:/app/logs