version: '3.8'

services:
  conversation-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434  # Point to local Ollama
      - OLLAMA_MODEL=llama2:latest  # Use the locally installed model name
      - SERVICE_HOST=llm-service
      - SERVICE_PORT=8080
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
      - JAVA_TOOL_OPTIONS=-Xmx512m
    volumes:
      - ./logs:/app/logs
    networks:
      - llm-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

networks:
  llm-network:
    name: llm-network  # Use the same network as the server
    external: true     # Ensure the network already exists

volumes:
  ollama_data: